# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: multimodal-bias

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: install
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.5.1
        poetry config virtualenvs.create false
        poetry install --with dev,test
        python -m spacy download en_core_web_md
    - name: lint
      run: |
        python -m black src
        ruff src
        isort src
    - name: test
      run: |
        python -m unittest
